version: "3.9"

services:
  image:
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/amd64
    working_dir: /workspace
    volumes:
      - .:/workspace
    stdin_open: true
    tty: true
